name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install buildozer
      - run: |
          echo '[app]
          title = SAFKATY
          package.name = safkaty
          package.domain = org.safkaty
          source.dir = .
          version = 1.0.0
          requirements = python3,flet
          orientation = portrait
          android.permissions = INTERNET
          android.api = 33' > buildozer.spec
      - run: buildozer android debug
      - uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: bin/*.apk
